// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cacheConfig.proto

#include "cacheConfig.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
class CacheConfigDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CacheConfig> _instance;
} _CacheConfig_default_instance_;
static void InitDefaultsscc_info_CacheConfig_cacheConfig_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CacheConfig_default_instance_;
    new (ptr) ::CacheConfig();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CacheConfig::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CacheConfig_cacheConfig_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_CacheConfig_cacheConfig_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_cacheConfig_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_cacheConfig_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_cacheConfig_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_cacheConfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::CacheConfig, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::CacheConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::CacheConfig, cache_size_),
  PROTOBUF_FIELD_OFFSET(::CacheConfig, line_size_),
  PROTOBUF_FIELD_OFFSET(::CacheConfig, associativity_),
  0,
  1,
  2,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::CacheConfig)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_CacheConfig_default_instance_),
};

const char descriptor_table_protodef_cacheConfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021cacheConfig.proto\"K\n\013CacheConfig\022\022\n\nca"
  "che_size\030\001 \002(\003\022\021\n\tline_size\030\002 \002(\005\022\025\n\rass"
  "ociativity\030\003 \002(\005"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_cacheConfig_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_cacheConfig_2eproto_sccs[1] = {
  &scc_info_CacheConfig_cacheConfig_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_cacheConfig_2eproto_once;
static bool descriptor_table_cacheConfig_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cacheConfig_2eproto = {
  &descriptor_table_cacheConfig_2eproto_initialized, descriptor_table_protodef_cacheConfig_2eproto, "cacheConfig.proto", 96,
  &descriptor_table_cacheConfig_2eproto_once, descriptor_table_cacheConfig_2eproto_sccs, descriptor_table_cacheConfig_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_cacheConfig_2eproto::offsets,
  file_level_metadata_cacheConfig_2eproto, 1, file_level_enum_descriptors_cacheConfig_2eproto, file_level_service_descriptors_cacheConfig_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_cacheConfig_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_cacheConfig_2eproto), true);

// ===================================================================

void CacheConfig::InitAsDefaultInstance() {
}
class CacheConfig::_Internal {
 public:
  using HasBits = decltype(std::declval<CacheConfig>()._has_bits_);
  static void set_has_cache_size(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_line_size(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_associativity(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

CacheConfig::CacheConfig()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CacheConfig)
}
CacheConfig::CacheConfig(const CacheConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&cache_size_, &from.cache_size_,
    static_cast<size_t>(reinterpret_cast<char*>(&associativity_) -
    reinterpret_cast<char*>(&cache_size_)) + sizeof(associativity_));
  // @@protoc_insertion_point(copy_constructor:CacheConfig)
}

void CacheConfig::SharedCtor() {
  ::memset(&cache_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&associativity_) -
      reinterpret_cast<char*>(&cache_size_)) + sizeof(associativity_));
}

CacheConfig::~CacheConfig() {
  // @@protoc_insertion_point(destructor:CacheConfig)
  SharedDtor();
}

void CacheConfig::SharedDtor() {
}

void CacheConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CacheConfig& CacheConfig::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CacheConfig_cacheConfig_2eproto.base);
  return *internal_default_instance();
}


void CacheConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:CacheConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&cache_size_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&associativity_) -
        reinterpret_cast<char*>(&cache_size_)) + sizeof(associativity_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* CacheConfig::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required int64 cache_size = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_cache_size(&has_bits);
          cache_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required int32 line_size = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_line_size(&has_bits);
          line_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required int32 associativity = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_associativity(&has_bits);
          associativity_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CacheConfig::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CacheConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int64 cache_size = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_cache_size(), target);
  }

  // required int32 line_size = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_line_size(), target);
  }

  // required int32 associativity = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_associativity(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CacheConfig)
  return target;
}

size_t CacheConfig::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:CacheConfig)
  size_t total_size = 0;

  if (_internal_has_cache_size()) {
    // required int64 cache_size = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_cache_size());
  }

  if (_internal_has_line_size()) {
    // required int32 line_size = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_line_size());
  }

  if (_internal_has_associativity()) {
    // required int32 associativity = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_associativity());
  }

  return total_size;
}
size_t CacheConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CacheConfig)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required int64 cache_size = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_cache_size());

    // required int32 line_size = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_line_size());

    // required int32 associativity = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_associativity());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CacheConfig::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CacheConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const CacheConfig* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CacheConfig>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CacheConfig)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CacheConfig)
    MergeFrom(*source);
  }
}

void CacheConfig::MergeFrom(const CacheConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CacheConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      cache_size_ = from.cache_size_;
    }
    if (cached_has_bits & 0x00000002u) {
      line_size_ = from.line_size_;
    }
    if (cached_has_bits & 0x00000004u) {
      associativity_ = from.associativity_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void CacheConfig::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CacheConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CacheConfig::CopyFrom(const CacheConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CacheConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CacheConfig::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void CacheConfig::InternalSwap(CacheConfig* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(cache_size_, other->cache_size_);
  swap(line_size_, other->line_size_);
  swap(associativity_, other->associativity_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CacheConfig::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CacheConfig* Arena::CreateMaybeMessage< ::CacheConfig >(Arena* arena) {
  return Arena::CreateInternal< ::CacheConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
