// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cacheConfig.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cacheConfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cacheConfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cacheConfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cacheConfig_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cacheConfig_2eproto;
class CacheConfig;
class CacheConfigDefaultTypeInternal;
extern CacheConfigDefaultTypeInternal _CacheConfig_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CacheConfig* Arena::CreateMaybeMessage<::CacheConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class CacheConfig :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CacheConfig) */ {
 public:
  CacheConfig();
  virtual ~CacheConfig();

  CacheConfig(const CacheConfig& from);
  CacheConfig(CacheConfig&& from) noexcept
    : CacheConfig() {
    *this = ::std::move(from);
  }

  inline CacheConfig& operator=(const CacheConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline CacheConfig& operator=(CacheConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CacheConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CacheConfig* internal_default_instance() {
    return reinterpret_cast<const CacheConfig*>(
               &_CacheConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CacheConfig& a, CacheConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(CacheConfig* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CacheConfig* New() const final {
    return CreateMaybeMessage<CacheConfig>(nullptr);
  }

  CacheConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CacheConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CacheConfig& from);
  void MergeFrom(const CacheConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CacheConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CacheConfig";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cacheConfig_2eproto);
    return ::descriptor_table_cacheConfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCacheSizeFieldNumber = 1,
    kLineSizeFieldNumber = 2,
    kAssociativityFieldNumber = 3,
  };
  // required int64 cache_size = 1;
  bool has_cache_size() const;
  private:
  bool _internal_has_cache_size() const;
  public:
  void clear_cache_size();
  ::PROTOBUF_NAMESPACE_ID::int64 cache_size() const;
  void set_cache_size(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_cache_size() const;
  void _internal_set_cache_size(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // required int32 line_size = 2;
  bool has_line_size() const;
  private:
  bool _internal_has_line_size() const;
  public:
  void clear_line_size();
  ::PROTOBUF_NAMESPACE_ID::int32 line_size() const;
  void set_line_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_line_size() const;
  void _internal_set_line_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 associativity = 3;
  bool has_associativity() const;
  private:
  bool _internal_has_associativity() const;
  public:
  void clear_associativity();
  ::PROTOBUF_NAMESPACE_ID::int32 associativity() const;
  void set_associativity(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_associativity() const;
  void _internal_set_associativity(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:CacheConfig)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int64 cache_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 line_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 associativity_;
  friend struct ::TableStruct_cacheConfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CacheConfig

// required int64 cache_size = 1;
inline bool CacheConfig::_internal_has_cache_size() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CacheConfig::has_cache_size() const {
  return _internal_has_cache_size();
}
inline void CacheConfig::clear_cache_size() {
  cache_size_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 CacheConfig::_internal_cache_size() const {
  return cache_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 CacheConfig::cache_size() const {
  // @@protoc_insertion_point(field_get:CacheConfig.cache_size)
  return _internal_cache_size();
}
inline void CacheConfig::_internal_set_cache_size(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  cache_size_ = value;
}
inline void CacheConfig::set_cache_size(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_cache_size(value);
  // @@protoc_insertion_point(field_set:CacheConfig.cache_size)
}

// required int32 line_size = 2;
inline bool CacheConfig::_internal_has_line_size() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CacheConfig::has_line_size() const {
  return _internal_has_line_size();
}
inline void CacheConfig::clear_line_size() {
  line_size_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CacheConfig::_internal_line_size() const {
  return line_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CacheConfig::line_size() const {
  // @@protoc_insertion_point(field_get:CacheConfig.line_size)
  return _internal_line_size();
}
inline void CacheConfig::_internal_set_line_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  line_size_ = value;
}
inline void CacheConfig::set_line_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_line_size(value);
  // @@protoc_insertion_point(field_set:CacheConfig.line_size)
}

// required int32 associativity = 3;
inline bool CacheConfig::_internal_has_associativity() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CacheConfig::has_associativity() const {
  return _internal_has_associativity();
}
inline void CacheConfig::clear_associativity() {
  associativity_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CacheConfig::_internal_associativity() const {
  return associativity_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CacheConfig::associativity() const {
  // @@protoc_insertion_point(field_get:CacheConfig.associativity)
  return _internal_associativity();
}
inline void CacheConfig::_internal_set_associativity(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  associativity_ = value;
}
inline void CacheConfig::set_associativity(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_associativity(value);
  // @@protoc_insertion_point(field_set:CacheConfig.associativity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cacheConfig_2eproto
